"""Ajustando relacionamento

Revision ID: bcd12761da06
Revises: a0a336ff7d48
Create Date: 2024-07-28 20:54:16.795081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd12761da06'
down_revision: Union[str, None] = 'a0a336ff7d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales_item', sa.Column('sale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sales_item', 'sales', ['sale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales_item', type_='foreignkey')
    op.drop_column('sales_item', 'sale_id')
    # ### end Alembic commands ###  
