"""Added column type user

Revision ID: d3e58c2d5ca0
Revises: 8f05ab362255
Create Date: 2024-07-27 14:25:10.257574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd3e58c2d5ca0'
down_revision: Union[str, None] = '8f05ab362255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'quantity_alert',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.add_column('users', sa.Column('type_user', sa.Enum('ADMIN', 'CLIENT', name='typeuserenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'type_user')
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    op.alter_column('products', 'quantity_alert',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
