"""Add seller product

Revision ID: dbee26f516d7
Revises: bcd12761da06
Create Date: 2024-07-30 14:29:07.277202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbee26f516d7'
down_revision: Union[str, None] = 'bcd12761da06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['seller_id'], ['id'])
    op.add_column('sales_item', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('sales_item', sa.Column('quantity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales_item', 'quantity')
    op.drop_column('sales_item', 'price')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
